- age(yrs)
- sex(0-Female , 1-Male)
- chest pain type (0 , 1 , 2 , 3)
- resting blood pressure (resting blood pressure (in mm Hg on admission to the hospital))
- serum cholestoral in mg/dl
- fasting blood sugar > 120 mg/dl (0-False , 1-True)
- resting electrocardiographic results (values 0,1,2)
- maximum heart rate achieved (thalach)
- exercise induced angina (exang) 1-Yes 0-No
- oldpeak = ST depression induced by exercise relative to rest
- the slope of the peak exercise ST segment
- number of major vessels (0-3) colored by flourosopy
- thal: 0 = normal; 1 = fixed defect; 2 = reversable defect
- The names and social security numbers of the patients were recently removed from the database, replaced with dummy values.

In [30]:
import numpy as np
import pandas as pd

In [31]:
df =  pd.read_csv('./data/heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [38]:
print("Total rows:", len(df))

print("Duplicate rows:", df.duplicated().sum())

print("Unique rows:", df.drop_duplicates().shape[0])

Total rows: 1025
Duplicate rows: 723
Unique rows: 302

In [39]:
duplicate_rows = df[df.duplicated(keep=False)]

duplicate_rows.sort_values(
    by=df.columns.tolist()
).head(20)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
60,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
64,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
118,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
668,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
12,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
779,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
143,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
201,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
572,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
256,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
501,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
841,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
846,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
254,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
701,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
711,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
912,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
384,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
695,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0

In [43]:
duplicate_rows.shape

(1025, 14)

In [32]:
df.shape

(1025, 14)